require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

# Use tabs for indentation with width of 4 spaces
Layout/IndentationStyle:
  EnforcedStyle: tabs

Layout/IndentationWidth:
  Width: 1  # 1 tab character
